controller_names:
  - stretch_arm_controller
  - gripper_controller

stretch_arm_controller:
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_lift
      - joint_arm_l3
      - joint_arm_l2
      - joint_arm_l1
      - joint_arm_l0
      - joint_wrist_yaw

gripper_controller:
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_gripper_finger_left
      - joint_gripper_finger_right