controller_manager:
  ros__parameters:
    update_rate: 2  # Hz

    stretch_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_controller:
      type: joint_state_controller/JointStateController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

stretch_arm_controller:
  ros__parameters:
    joints:
      - joint_lift
      - joint_arm_l3
      - joint_arm_l2
      - joint_arm_l1
      - joint_arm_l0
      - joint_wrist_yaw

gripper_controller:
  ros__parameters:
    joints:
      - joint_gripper_finger_left
      - joint_gripper_finger_right
